"""
strainmake build - generate a Snakefile from a StrainMake configuration YAML.

Wraps the Jinja2 template at workflow/scripts/config_generator/Snakefile.j2,
resolving the template path relative to the installed package.
"""

from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import List, Optional, Set

import typer
import yaml
from jinja2 import Environment, FileSystemLoader

from strainmake import REPO_ROOT

# ---------------------------------------------------------------------------
# Constants & validated CLI choices
# ---------------------------------------------------------------------------

_TEMPLATE_FILE: Path = (
    REPO_ROOT / "workflow" / "scripts" / "config_generator" / "Snakefile.j2"
)

# maps each --perform step to the config top-level key that enables it.
# a value of None means the step is always included (no config key needed).
_STEP_CONFIG_KEY: dict = {
    "preprocessing": None,
    "assembly": "assembly",
    "binning": "binning",
    "postprocessing": "binning",    # lives under the binning config section
    "taxo_profiling": "taxonomic_profiling",
    "strain_profiling": "strains_profiling",
}


class PerformStep(str, Enum):
    preprocessing = "preprocessing"
    assembly = "assembly"
    binning = "binning"
    postprocessing = "postprocessing"
    taxo_profiling = "taxo_profiling"
    strain_profiling = "strain_profiling"


class StrainProfilingTool(str, Enum):
    instrain = "instrain"
    floria = "floria"


class TaxonomicProfilingTool(str, Enum):
    meteor = "meteor"
    metaphlan = "metaphlan"
    strainscan = "strainscan"


class PostProcessingTool(str, Enum):
    gtdbtk = "gtdbtk"
    coverage = "coverage"   # maps to the checkm1 rule
    carveme = "carveme"
    bakta = "bakta"


# ---------------------------------------------------------------------------
# Typer command
# ---------------------------------------------------------------------------


def build(
    config: Path = typer.Option(
        ...,
        "--config",
        "-c",
        help="Path to the StrainMake configuration YAML (generated by `strainmake init`).",
        exists=True,
        readable=True,
    ),
    output: Path = typer.Option(
        "Snakefile",
        "--output",
        "-o",
        help="Path to write the generated Snakefile.",
    ),
    perform: Optional[List[PerformStep]] = typer.Option(
        None,
        "--perform",
        help=(
            "Pipeline step(s) to include. Pass once per step, e.g. "
            "`--perform assembly --perform binning`. "
            "If omitted, all steps present in the config are included."
        ),
    ),
    strain_profiling_tools: Optional[List[StrainProfilingTool]] = typer.Option(
        None,
        "--strain-profiling",
        help=(
            "Strain profiling tool(s) to include: instrain, floria. "
            "Pass once per tool. Automatically activates 'strain_profiling' "
            "even without an explicit --perform flag. "
            "If omitted, all tools are included."
        ),
    ),
    post_processing_tools: Optional[List[PostProcessingTool]] = typer.Option(
        None,
        "--post-processing",
        help=(
            "Post-processing tool(s) to include: gtdbtk, coverage (checkm1), carveme, bakta. "
            "Pass once per tool. Automatically activates 'postprocessing' "
            "even without an explicit --perform flag. "
            "If omitted, all tools are included."
        ),
    ),
    taxonomic_profiling_tools: Optional[List[TaxonomicProfilingTool]] = typer.Option(
        None,
        "--taxonomic-profiling",
        help=(
            "Taxonomic profiling tool(s) to include: meteor, metaphlan, strainscan. "
            "Pass once per tool. Automatically activates 'taxo_profiling' "
            "even without an explicit --perform flag. "
            "If omitted, all tools are included."
        ),
    ),
) -> None:
    """
    Generate a [bold]Snakefile[/bold] from a StrainMake configuration YAML.

    By default all sections present in the config are rendered. Use [cyan]--perform[/cyan]
    to restrict to specific pipeline steps, and [cyan]--post-processing[/cyan],
    [cyan]--taxonomic-profiling[/cyan], or [cyan]--strain-profiling[/cyan]
    for finer granularity within those steps.

    \b
    Examples:
        # All steps (config-driven, default):
        strainmake build --config config.yaml

        # Only assembly + binning:
        strainmake build --config config.yaml --perform assembly --perform binning

        # Post-processing with a subset of tools:
        strainmake build --config config.yaml \\
            --perform assembly --perform binning --perform postprocessing \\
            --post-processing gtdbtk --post-processing carveme

        # Taxonomic profiling with Meteor only:
        strainmake build --config config.yaml \\
            --perform taxo_profiling --taxonomic-profiling meteor

        # Strain profiling with only inStrain:
        strainmake build --config config.yaml \\
            --perform assembly --perform binning --perform postprocessing \\
            --perform strain_profiling --strain-profiling instrain
    """
    if not _TEMPLATE_FILE.exists():
        typer.echo(
            f"❌  Snakefile template not found: {_TEMPLATE_FILE}\n"
            "Make sure you run `strainmake build` from the repo root.",
            err=True,
        )
        raise typer.Exit(1)

    with open(config, encoding="utf-8") as fh:
        config_data = yaml.safe_load(fh)

    # converting option lists to sets (None = "not specified" → use config or render all)
    pp_tools: Optional[Set[str]] = (
        {t.value for t in post_processing_tools} if post_processing_tools else None
    )
    sp_tools: Optional[Set[str]] = (
        {t.value for t in strain_profiling_tools} if strain_profiling_tools else None
    )
    tp_tools: Optional[Set[str]] = (
        {t.value for t in taxonomic_profiling_tools} if taxonomic_profiling_tools else None
    )

    # sub-tool flags implicitly activate their parent step even without --perform.
    perform_set: Optional[Set[str]] = {p.value for p in perform} if perform else None
    if perform_set is not None:
        if pp_tools is not None:
            perform_set.add("postprocessing")
        if tp_tools is not None:
            perform_set.add("taxo_profiling")
        if sp_tools is not None:
            perform_set.add("strain_profiling")

    def _include(step: str) -> bool:
        """True when this pipeline step should be rendered into the Snakefile."""
        if perform_set is not None:
            return step in perform_set
        # Config-driven fallback when no --perform was given
        config_key = _STEP_CONFIG_KEY.get(step)
        if config_key is None:
            return True  # e.g. preprocessing — always on when not filtered
        return bool(config_data.get(config_key))

    # setting up the Jinja2 environment to load templates from the template's directory
    env = Environment(
        loader=FileSystemLoader(str(_TEMPLATE_FILE.parent)),
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    template_obj = env.get_template(_TEMPLATE_FILE.name)

    # rendering the template with the config data and metadata about generation time and included steps/tools
    rendered = template_obj.render(
        config=config_data,
        config_path=str(config),
        generation_datetime=datetime.now().isoformat(),
        do_preprocessing=_include("preprocessing"),
        do_assembly=_include("assembly"),
        do_binning=_include("binning"),
        do_postprocessing=_include("postprocessing"),
        do_taxo_profiling=_include("taxo_profiling"),
        do_strain_profiling=_include("strain_profiling"),
        pp_tools=pp_tools,   # None → render all post-processing tools
        tp_tools=tp_tools,   # None → render all taxonomic profiling tools
        sp_tools=sp_tools,   # None → render all strain profiling tools
    )

    # writing the rendered Snakefile to disk
    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, "w", encoding="utf-8") as fh:
        fh.write(rendered)

    typer.echo(f"✅  Snakefile generated at [bold]{output}[/bold]")
