"""
strainmake run - run the StrainMake pipeline via Snakemake.

Wraps `snakemake --use-conda` with sensible defaults.
Any extra positional arguments are forwarded verbatim to Snakemake.
"""

import json
import re
from pathlib import Path
from typing import List, Optional, Tuple

import typer

from strainmake import REPO_ROOT
from strainmake.cli._snakemake import run_snakemake
from strainmake.databases import (
    conda_prefix,
    inspect_databases,
    load_config,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_DEFAULT_SNAKEFILE: Path = REPO_ROOT / "workflow" / "Snakefile"
_PREPROCESSED_SNAKEFILE: Path = (
    REPO_ROOT / "workflow" / "Snakefile.already_preprocessed_seq.smk"
)


# a `configfile:` line at the top of a Snakefile, as `strainmake build` writes
# and as the shipped Snakefiles carry
_CONFIGFILE_RE = re.compile(
    r"""^configfile:\s*["'](?P<path>[^"']+)["']""", re.MULTILINE
)


# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------


def _embedded_configfile(snakefile: Path) -> Optional[Path]:
    """
    Find the configuration a Snakefile loads on its own.

    Every Snakefile StrainMake runs (shipped or generated by `strainmake
    build`) names its own config, which is why a run works without --config.
    That would otherwise leave the most common invocation of all as the one
    that gets no database checks, and would leave `--offline` unable to see
    the environment directory it depends on.

    Parameters:
    snakefile (Path): the Snakefile about to be run

    Returns:
    Path or None: the configuration it references, if that file exists
    """

    try:
        text = snakefile.read_text(encoding="utf-8")
    except OSError:
        return None

    match = _CONFIGFILE_RE.search(text)
    if not match:
        return None

    # Snakemake resolves a relative configfile against the working directory
    candidate = Path(match.group("path"))

    return candidate if candidate.is_file() else None


def _preflight(config_data: dict, offline: bool) -> Tuple[List[str], List[str]]:
    """
    Check that everything this run reads from disk is actually on disk.

    What a missing database means depends on whether the run can reach the
    network, so the two cases are reported differently:

    * offline, it is fatal, no amount of running will produce the database,
      and the alternative is a wall of connection retries deep into the run;
    * online, it is a warning, the pipeline downloads it as it always has, but
      the user is told up front, because "it downloads what it needs" and "it is
      about to spend an hour pulling 101 GiB" deserve different reactions.

    A database StrainMake cannot download at all is fatal either way.

    Parameters:
    config_data (dict): the pipeline configuration
    offline (bool): whether the run was asked to avoid the network

    Returns:
    tuple: (errors, warnings), both human-readable; no errors means it can run
    """

    errors: List[str] = []
    warnings: List[str] = []

    for status in inspect_databases(config_data).values():
        if not status.blocking:
            continue

        where = f"{status.label} database not found at '{status.path}'"

        if not status.downloadable:
            hint = "\n      → install it manually"
            if status.manual_source:
                hint += f", see {status.manual_source}"
            errors.append(where + hint)
        elif offline:
            errors.append(
                where
                + "\n      → run `strainmake fetch-databases` on a machine with "
                "internet access"
            )
        else:
            size = f" ({status.approx_size})" if status.approx_size else ""
            warnings.append(
                f"{status.label} database is missing and will be downloaded{size}"
                f" to '{status.path}'"
            )

    if offline:
        prefix = conda_prefix(config_data)

        if prefix is None:
            errors.append(
                "no shared conda environment directory is configured"
                "\n      → set `deployment: conda_prefix:` to a directory on shared"
                "\n        storage, and build the environments into it from a machine"
                "\n        with internet access:"
                "\n        strainmake run --config <config.yaml> --create-envs-only"
            )
        elif not Path(prefix).is_dir():
            errors.append(
                f"conda environments not found at '{prefix}'"
                "\n      → build them where there is internet access:"
                "\n        strainmake run --config <config.yaml> --create-envs-only"
            )

    return errors, warnings


# ---------------------------------------------------------------------------
# Typer command
# ---------------------------------------------------------------------------


def run(
    ctx: typer.Context,
    snakefile: Path = typer.Option(
        _DEFAULT_SNAKEFILE,
        "--snakefile",
        "-s",
        help="Path to the Snakefile to execute.",
    ),
    cores: int = typer.Option(
        4,
        "--cores",
        "-c",
        min=1,
        help="Number of CPU cores to use.",
    ),
    configfile: Optional[Path] = typer.Option(
        None,
        "--configfile",
        "--config",
        "-C",
        help="Path to a config YAML (passed via --configfile to Snakemake).",
        exists=True,
        readable=True,
    ),
    already_preprocessed: bool = typer.Option(
        False,
        "--already-preprocessed",
        help=(
            "Start from already-preprocessed reads "
            "(uses Snakefile.already_preprocessed_seq.smk)."
        ),
    ),
    create_envs_only: bool = typer.Option(
        False,
        "--create-envs-only",
        help=(
            "Build the pipeline's conda environments and stop, without running "
            "anything. Run this where there is internet access, with "
            "`deployment: conda_prefix:` pointing at shared storage."
        ),
    ),
    offline: bool = typer.Option(
        False,
        "--offline",
        help=(
            "Run without any internet access. Requires the conda environments "
            "to have been built beforehand (--create-envs-only) and the "
            "databases fetched (`strainmake fetch-databases`)."
        ),
    ),
    skip_checks: bool = typer.Option(
        False,
        "--skip-checks",
        help="Skip the preflight database checks.",
    ),
    dry_run: bool = typer.Option(
        False,
        "--dry-run",
        "-n",
        help="Dry run: print rules that would be executed without running them.",
    ),
) -> None:
    """
    Run the [bold]StrainMake[/bold] pipeline using Snakemake.

    Wraps [cyan]snakemake --use-conda[/cyan] with sensible defaults.
    Any unknown options/flags are passed through to Snakemake unchanged.
    Use [cyan]--[/cyan] to separate StrainMake options from Snakemake ones:

    \b
        strainmake run --cores 16
        strainmake run --cores 8 --configfile my_config.yaml
        strainmake run --already-preprocessed --cores 8
        strainmake run --dry-run
        strainmake run --cores 16 -- --rerun-incomplete --keep-going

    On a cluster whose compute nodes have no internet access, prepare the
    environments and databases once from a machine that does, then run offline:

    \b
        # on the login node
        strainmake run --config my_config.yaml --create-envs-only
        strainmake fetch-databases --config my_config.yaml
        # on the compute nodes
        strainmake run --config my_config.yaml --offline --cores 64
    """
    effective_snakefile = _PREPROCESSED_SNAKEFILE if already_preprocessed else snakefile

    # StrainMake needs to read the configuration itself, for the database
    # checks, and to tell Snakemake where the prebuilt environments live, but
    # the user should not have to pass it twice: fall back to the one the
    # Snakefile already names.
    config_source = configfile or _embedded_configfile(effective_snakefile)

    # Offline cannot proceed without one. The environment directory reaches
    # Snakemake as a command-line option, and the offline override replaces the
    # whole `deployment` mapping the Snakefile loaded, which would discard the
    # very conda_prefix the run depends on.
    if offline and config_source is None:
        typer.echo(
            "❌  --offline needs the configuration, and none was found.\n"
            "    Pass --config <config.yaml>: StrainMake has to read\n"
            "    `deployment: conda_prefix:` to tell Snakemake where the\n"
            "    prebuilt environments are.",
            err=True,
        )
        raise typer.Exit(1)

    config_data = load_config(config_source) if config_source else {}

    # --create-envs-only builds conda environments and stops; it reads no
    # database, so checking for them here would block the very command a user
    # runs first, before fetching anything
    if not skip_checks and config_source and not create_envs_only:
        errors, warnings = _preflight(config_data, offline)

        for warning in warnings:
            typer.echo(f"⚠️   {warning}", err=True)
        if warnings:
            typer.echo(
                "    Fetch them ahead of time with `strainmake fetch-databases`.\n",
                err=True,
            )

        if errors:
            typer.echo("❌  StrainMake cannot start:\n", err=True)
            for error in errors:
                typer.echo(f"  • {error}\n", err=True)
            typer.echo(
                "Re-run with --skip-checks to attempt the run anyway.", err=True
            )
            raise typer.Exit(1)

    cmd: List[str] = [
        "snakemake",
        "--snakefile", str(effective_snakefile),
        "--use-conda",
        "--cores", str(cores),
    ]

    if configfile:
        cmd += ["--configfile", str(configfile)]

    # a shared environment directory is what lets the environments be built once,
    # where there is internet access, and reused where there is none
    prefix = conda_prefix(config_data)
    if prefix:
        cmd += ["--conda-prefix", prefix]

    if create_envs_only:
        cmd.append("--conda-create-envs-only")

    if offline:
        # tell the workflow it has no network, so that any download rule left in
        # the DAG fails immediately with a message naming the database, instead
        # of retrying against an unreachable host.
        # the whole `deployment` mapping is resent because --config replaces a
        # top-level key rather than merging into it
        deployment = dict(config_data.get("deployment") or {})
        deployment["offline"] = True
        cmd += ["--config", f"deployment={json.dumps(deployment)}"]

    if dry_run:
        cmd.append("--dry-run")

    if ctx.args:
        cmd.extend(ctx.args)

    returncode = run_snakemake(cmd)

    if create_envs_only and returncode == 0 and prefix:
        # Snakemake stores an environment under a hash of, among other things,
        # the resolved path of this directory. If it resolves differently on the
        # compute nodes, every environment is considered missing and rebuilt,
        # which is exactly what fails there. Surface the resolved path so it can
        # be compared before that happens.
        typer.echo(
            f"\n✅  Conda environments built in {Path(prefix).resolve()}\n"
            "    Check that path resolves identically on the compute nodes "
            f"(`realpath {prefix}`);\n"
            "    Snakemake treats a different path as a different set of "
            "environments."
        )

    raise typer.Exit(code=returncode)
