""" 
Script for replacing space by a period in FASTA headers generated by MEGAHIT
"""

import sys
import logging

def replace_spaces_in_fasta(input_file, output_file):
    logging.info(f"Opening input file: {input_file}")
    
    with open(input_file, 'r') as infile, open(output_file, 'w') as outfile:
        modified_headers = 0
        total_headers = 0

        for line in infile:
            if line.startswith('>'):
                total_headers += 1
                if ' ' in line:
                    modified_headers += 1
                    logging.debug(f"Modifying header: {line.strip()}")
                    line = line.replace(' ', '.')
            outfile.write(line)

    logging.info(f"Finished processing. Total headers: {total_headers}, Modified headers: {modified_headers}")
    logging.info(f"Output written to: {output_file}")

if __name__ == "__main__":
    # Configure logging
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

    if len(sys.argv) != 3:
        print("Usage: python megahit_fasta_header_rename.py <input.fasta> <output.fasta>")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    logging.info("Starting the header replacement process.")
    replace_spaces_in_fasta(input_file, output_file)
    logging.info("Process completed.")