"""
Script for replacing space by a period in FASTA headers generated by MEGAHIT
"""

import sys

def replace_spaces_in_fasta(input_file, output_file):
    with open(input_file, 'r') as infile, open(output_file, 'w') as outfile:
        for line in infile:
            if line.startswith('>'):
                line = line.replace(' ', '.')
            outfile.write(line)

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python megahit_fasta_header_rename.py <input.fasta> <output.fasta>")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]
    replace_spaces_in_fasta(input_file, output_file)