samples:
  - ERR1855257

################################################################################
#                                Preprocessing                                 #        
################################################################################ 

fastp:
  compression: 2 # --compression command of fastp
  minimal_read_length: 50 # --length_required command of fastp
  qualified_quality_phred: 15 # quality value (phred) that a base is qualified

bowtie2:
  index_name: GRCh38_noalt_as # for human. See others at https://bowtie-bio.sourceforge.net/bowtie2/manual.shtml
  threads: 4

################################################################################
#                                   Assembly                                   #        
################################################################################        

assembler: megahit # to be implemented (megahit, metaspades, idbaud...)

# MEGAHIT configuration
megahit:
  threads: 4

# SPAdes configuration
metaspades:
  threads: 4

################################################################################
#                               Assembly quality                               #
################################################################################

quast:
  threads: 4

################################################################################
#                                   Binning                                    #
################################################################################

binning:
  binner: metabat2 # to be implemented (vamb, semibin2...)
  # bowtie2 configuration for both indexing and mapping
  bowtie2:
    threads: 4 # for both indexing and mapping
    seed: 199999
  # MetaBAT 2 configuration
  metabat2:
    min_contig_size: 1500 # minimun size of 1500 bp per the MetaBAT 2 doc
    minimum_mean_coverage: 1 # minimum mean coverage of a contig in each library for binning
    min_bin_size: 200000 # minimum size of a bin as the output
    threads: 4 # put 0 for using all cores
  semibin2:
    environment: ocean # (human_gut, dog_cut, ocean...) see https://semibin.readthedocs.io/en/latest/usage/#easy-single-binning-mode
    threads: 4 # put 0 for using all cores

################################################################################
#                                 Bins quality                                 #
################################################################################

checkm2:
  threads: 4